video_game_sequence:
    resource: "@VideoGameBundle/Controller/SequenceController.php"
    type:     annotation

video_game_game:
    resource: "@VideoGameBundle/Controller/GameController.php"
    type:     annotation

admin:
    prefix:  /admin
    resource: "@VideoGameBundle/Controller/AdminController.php"
    type:     annotation

videogame:
    path:  /
    defaults: { _controller: VideoGameBundle:VideoGame:index }
    requirements:
       _method:  GET

game:
    path:  /game/{idName}
    defaults: { _controller: VideoGameBundle:VideoGame:game }
    requirements:
       _method:  GET
