
videogame:
    path:  /
    defaults: { _controller: VideoGameBundle:VideoGame:index }
    requirements:
       _method:  GET

game:
    path:  /game/{idName}
    defaults: { _controller: VideoGameBundle:VideoGame:game }
    requirements:
       _method:  GET

mobile_game:
    path:  /game/m/{idName}
    defaults: { _controller: VideoGameBundle:VideoGame:mobileGame }
    requirements:
       _method:  GET
